# Generated by Django 3.0.5 on 2020-04-24 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('sport', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, help_text='Enter some event details', max_length=1000, null=True)),
                ('total_slots', models.IntegerField()),
                ('status', models.CharField(choices=[('o', 'Upcoming'), ('f', 'Filled'), ('c', 'Cancelled'), ('d', 'Done')], default='o', max_length=1)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Event')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
